### ISSUE TITLE
Format of messages in slack

### ISSUE THREAD

**Issue by tg-tomer** [assertible/lambda-cloudwatch-slack#22]
Hi,
I'm testing your code with the following configuration:

1. Cloudwatch alarm created on Redshift is sent to SNS topic
2. SNS topic is set as trigger for the Lambda

Expected result:
![Alt text](https://raw.githubusercontent.com/assertible/lambda-cloudwatch-slack/master/images/cloudwatch.png)

Actual result:
![Alt text](http://i64.tinypic.com/j0uy4g.png "Optional title")

Can you help please?

**Comment by CodyReichert** [comment]
Hey @tg-tomer - thanks for opening! We recently added a 'default' message format for alarms that don't match one of the pre-formatted ones. It looks like your second picture is hitting that default case, so it's not formatted like in the first picture.

Did you close this because you got it working? I can take a look if you're still seeing this, just post your JSON even (remove any sensitive info).

**Comment by JonFranchi** [comment]
I have this exact same problem.

**Comment by JonFranchi** [comment]
I think I see what's going on.  It looks like possibly custom metrics don't get `CloudWatchNotifications` in the ARN, or that it no longer puts it in the ARN at all.  I only have this custom metric example at the moment, but `eventSubscriptionArn` does not include that string and neither does `TopicArn`.

I wonder if there is something I can modify to get it to say cloudwatch somewhere, because otherwise the formatting is perfect.

**Comment by JonFranchi** [comment]
As far as I can tell, this would only work if you created an SNS topic called `CloudWatchNotifications` and directed every alarm to notify there.  Is it the case that this used to happen by default and thats how it got written that way?  I think it would be helpful to include this in the documentation if that's the intended way to utilize this.
